# Generated by Django 5.2.5 on 2025-08-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotesapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="click_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
